var uname = "malik rimsha";
var ulocation = "karachi";
var marks = 500;
var percentage = 80;
console.log("name:", uname);
console.log("location:", ulocation);
console.log("marks", marks);
console.log("percentage", percentage);
var str = "1";
var str2 = str;
console.log(typeof (str2));
var num = 2;
console.log("valus of num", " ", "my lucky number", " ", +num);
num = 7;
console.log(num);
